export const MAIL_LIST_REQUEST = "MAIL_LIST_REQUEST";
export const MAIL_LIST_SUCCESS = "MAIL_LIST_SUCCESS";
export const MAIL_LIST_FAILED = "MAIL_LIST_FAILED";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const MAIL_BODY_REQUEST = "MAIL_BODY_REQUEST";
export const MAIL_BODY_SUCCESS = "MAIL_BODY_SUCCESS";
export const MAIL_BODY_FAILED = "MAIL_BODY_FAILED";
